name: Build Packages
on:
  push:

env:
  APTLY_VERSION: "1.5.0"
  REGISTRY: "ghcr.io"
  REPO_REGION: "eu-central-1"
  REPO_BUCKET: "apt.aws.chainflip.xyz"

jobs:
  build-deb:
    name: Publish packages to the repository
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "### Packages published! :rocket:" >> $GITHUB_STEP_SUMMARY

          echo "Packages can be installed with the following commands: " >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY

          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY

          echo "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys xxxxx" >> $GITHUB_STEP_SUMMARY

          echo "echo \"deb https://{user}:{password}@${REPO_BUCKET}/ci/$xxxx/ xxxxx main\"  | sudo tee /etc/apt/sources.list.d/chainflip list" >> $GITHUB_STEP_SUMMARY

          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "After these steps, run *apt update* and install the desired packages" >> $GITHUB_STEP_SUMMARY
